### ISSUE TITLE
Chat Clear Lag

### ISSUE THREAD

**Issue by ghost** [TheRealFrostedWeFall/ChatCore2.0#1]
Could you make the clear chat feature less laggy. You should probably make it like this amazing Skript: https://www.spigotmc.org/resources/simplechat-2-powerful-chat-management-skript-beta-1-7-1-12.49461/

but dont copy me pls

**Comment by FrostedWeFall** [comment]
Yes I will be looking into this issue into further detail.

**Comment by TheRealFrostedWeFall** [comment]
Now fixed by changing code. Before it cleared 300 lines, now clears 150! Update coming on spigot very soon
